### PR TITLE
pycodcif: add README as long_description

### PR DESCRIPTION
**Pull request by ltalirz**
* add README.rst as content of long_description
   in setup.py so that it will appear on pypi
 * add url to github mirror as "source url"
 * very minor changes in README.rst

### CODE REVIEW

**Comment by ltalirz** [comment]
Hi @merkys, here comes a long overdue PR for the pycodcif wrapper.
By the way, I just tested `pip install`ing it on my Mac and now it works fine.
Very nice!

**Comment by ltalirz** [comment]
By the way, there's also some progress on the CIF validator tool for Materials Cloud that I talked about (using `pycodcif`) - will keep you updated

**Comment by merkys** [comment]
@ltalirz thanks a lot for the PR and reports on `pycodcif` usage! I will merge your PR shortly.

**Comment by merkys** [comment]
I've applied the diff of this PR to the code in cod-tools Subversion repository. Thus the PR is merged, so I close it. Thanks once more @ltalirz!

**Pull request closed without merging**
